/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'


export default function Home() {
  const [image, setImage] = useState<string | ArrayBuffer | null>(null);
  const [cnt, setCnt] = useState(0);
  const getImage = () => {
    fetch("https://poticket.interpark.com/CommonAPI/Captcha/")
      .then(res => res.blob())
      .then(res => {
        let reader = new FileReader();
        reader.readAsDataURL(res);
        reader.onloadend = () => {
          let base64data = reader.result;
          // console.log(base64data);
          setImage(base64data);
        }
      });
  }

  const handleSubmit = (e: React.SyntheticEvent) => {
    e.preventDefault();
    const target = e.target as typeof e.target & {
      input: { value: string };
    }
    console.log(target.input.value.toUpperCase());
    
    // print(e.)
  }

  useEffect(() => {
    getImage();
  }, []);

  return (
    <>
      <Head>
        <title>captcha datagen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container mx-auto'>
        <div>
          <span>{cnt}</span>
        </div>
        <form onSubmit={handleSubmit}>
          <div className='mb-6'>
            <img src={image as string} alt="captcha"/>
          </div>
          <div className='mb-6'>
            <input type="text" name='input' autoComplete="off" style={{'textTransform': "uppercase"}} id="answer" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="XAAABZ" required />
          </div>
          <button type="submit" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
        </form>
      </main>
    </>
  )
}
