import Head from "next/head"
import { useEffect, useMemo, useState } from "react";

export default function Header() {
  const [focus, setFocus] = useState(1);
  const matches = Number(window?.matchMedia('(prefers-color-scheme: dark)').matches);
  
  const handleFocus = () => {
    setFocus(1);
  };
  const handleBlur = () => {
    setFocus(0);
  };

  useEffect(() => {
    window.addEventListener("focus", handleFocus);
    window.addEventListener("blur", handleBlur);

    return () => {
      window.removeEventListener("focus", handleFocus);
      window.removeEventListener("blur", handleBlur);
    }
  }, []);  
  
  return (
    <Head>
      <title>captcha datagen</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href={(matches ^ focus) ? "/logob.ico" : "/logow.ico"} />
    </Head>
  );
}